" ${themeName} Vim/Neovim Theme
" Generated by RLabs Theme Generator
" Using sacred geometry principles

" UI Colors
let g:colors = {
  \ 'bg1': '${BG1}',
  \ 'bg2': '${BG2}',
  \ 'bg3': '${BG3}',
  \ 'fg1': '${FG1}',
  \ 'fg2': '${FG2}',
  \ 'fg3': '${FG3}',
  \ 'ac1': '${AC1}',
  \ 'ac2': '${AC2}',
  \ 'border': '${BORDER}',
  \ 'info': '${INFO}',
  \ 'error': '${ERROR}',
  \ 'warning': '${WARNING}',
  \ 'success': '${SUCCESS}',
  \ 'line_highlight': '${lineHighlight}',
  \ 'selection': '${selection}',
  \ 'find_match': '${findMatch}'
\ }

" Syntax Colors
let g:syntax_colors = {
  \ 'keyword': '${keyword}',
  \ 'comment': '${comment}',
  \ 'function': '${function}',
  \ 'function_call': '${functionCall}',
  \ 'method': '${method}',
  \ 'method_call': '${methodCall}',
  \ 'variable': '${variable}',
  \ 'variable_readonly': '${variableReadonly}',
  \ 'variable_declaration': '${variableDeclaration}',
  \ 'variable_property': '${variableProperty}',
  \ 'type': '${type}',
  \ 'type_parameter': '${typeParameter}',
  \ 'constant': '${constant}',
  \ 'class': '${class}',
  \ 'parameter': '${parameter}',
  \ 'property': '${property}',
  \ 'property_declaration': '${propertyDeclaration}',
  \ 'operator': '${operator}',
  \ 'storage': '${storage}',
  \ 'other': '${other}',
  \ 'language': '${language}',
  \ 'support_variable': '${supportVariable}',
  \ 'support_function': '${supportFunction}',
  \ 'support_method': '${supportMethod}',
  \ 'support_property': '${supportProperty}',
  \ 'punctuation': '${punctuation}',
  \ 'punctuation_quote': '${punctuationQuote}',
  \ 'punctuation_brace': '${punctuationBrace}',
  \ 'punctuation_comma': '${punctuationComma}',
  \ 'selector': '${selector}',
  \ 'support': '${support}',
  \ 'modifier': '${modifier}',
  \ 'control': '${control}',
  \ 'control_flow': '${controlFlow}',
  \ 'control_import': '${controlImport}',
  \ 'tag': '${tag}',
  \ 'tag_punctuation': '${tagPunctuation}',
  \ 'attribute': '${attribute}',
  \ 'unit': '${unit}',
  \ 'datetime': '${datetime}'
\ }

" ANSI Colors
let g:ansi_colors = {
  \ 'black': '${Black}',
  \ 'red': '${Red}',
  \ 'green': '${Green}',
  \ 'yellow': '${Yellow}',
  \ 'blue': '${Blue}',
  \ 'magenta': '${Magenta}',
  \ 'cyan': '${Cyan}',
  \ 'white': '${White}',
  \ 'bright_black': '${BrightBlack}',
  \ 'bright_red': '${BrightRed}',
  \ 'bright_green': '${BrightGreen}',
  \ 'bright_yellow': '${BrightYellow}',
  \ 'bright_blue': '${BrightBlue}',
  \ 'bright_magenta': '${BrightMagenta}',
  \ 'bright_cyan': '${BrightCyan}',
  \ 'bright_white': '${BrightWhite}'
\ }

set background=${background}

" Base colors
highlight Normal guifg=${FG1} guibg=${BG1}

" Comments
highlight Comment guifg=${comment} gui=italic
highlight SpecialComment guifg=${comment} gui=italic
highlight Todo guifg=${WARNING} guibg=NONE gui=bold
highlight @comment guifg=${comment} gui=italic
highlight @comment.documentation guifg=${comment} gui=italic
highlight @comment.todo guifg=${WARNING} gui=bold
highlight @comment.note guifg=${WARNING} gui=bold
highlight @comment.warning guifg=${WARNING} gui=bold
highlight @comment.error guifg=${ERROR} gui=bold
highlight @comment.fixme guifg=${WARNING} gui=bold
highlight @comment.hack guifg=${WARNING} gui=bold

" Basic syntax
highlight String guifg=${FG1}
highlight Emphasis gui=italic
highlight Strong gui=bold
highlight Invalid guifg=${ERROR} guibg=${BG2} gui=strikethrough
highlight @deprecated guifg=${WARNING} gui=underline,italic
highlight Title guifg=${AC2}

" UI elements
highlight Cursor guifg=${BG1} guibg=${FG1}
highlight LineNr guifg=${comment}
highlight CursorLineNr guifg=${AC1}
highlight VertSplit guifg=${BORDER} guibg=NONE
highlight ColorColumn guibg=${BG2}
highlight SignColumn guibg=${BG1}
highlight Visual guibg=${selection}
highlight VisualNOS guibg=${selection}
highlight IncSearch guifg=${FG1} guibg=${findMatch}
highlight Search guifg=${FG1} guibg=${findMatch}
highlight MatchParen guibg=${lineHighlight}
highlight Folded guifg=${comment} guibg=${BG2}
highlight FoldColumn guifg=${comment} guibg=${BG1}
highlight NonText guifg=${comment}
highlight Whitespace guifg=${comment}
highlight SpecialKey guifg=${comment}
highlight EndOfBuffer guifg=${BG1}

" Status Line
highlight StatusLine guifg=${FG1} guibg=${AC2}
highlight StatusLineNC guifg=${comment} guibg=${BG2}
highlight WildMenu guifg=${FG1} guibg=${selection}
highlight ModeMsg guifg=${AC1}
highlight MoreMsg guifg=${AC1}
highlight Question guifg=${AC1}
highlight WarningMsg guifg=${WARNING}
highlight ErrorMsg guifg=${ERROR} guibg=${BG1}

" Popup Menu
highlight Pmenu guifg=${FG1} guibg=${BG2}
highlight PmenuSel guifg=${FG1} guibg=${selection}
highlight PmenuSbar guibg=${BG3}
highlight PmenuThumb guibg=${FG2}

" Tabs
highlight TabLine guifg=${comment} guibg=${BG3}
highlight TabLineFill guifg=${BORDER} guibg=${BG1}
highlight TabLineSel guifg=${FG1} guibg=${BG2}

" Terminal Colors
let g:terminal_color_0 = '${Black}'
let g:terminal_color_1 = '${Red}'
let g:terminal_color_2 = '${Green}'
let g:terminal_color_3 = '${Yellow}'
let g:terminal_color_4 = '${Blue}'
let g:terminal_color_5 = '${Magenta}'
let g:terminal_color_6 = '${Cyan}'
let g:terminal_color_7 = '${White}'
let g:terminal_color_8 = '${BrightBlack}'
let g:terminal_color_9 = '${BrightRed}'
let g:terminal_color_10 = '${BrightGreen}'
let g:terminal_color_11 = '${BrightYellow}'
let g:terminal_color_12 = '${BrightBlue}'
let g:terminal_color_13 = '${BrightMagenta}'
let g:terminal_color_14 = '${BrightCyan}'
let g:terminal_color_15 = '${BrightWhite}'

" Syntax highlighting
highlight Constant guifg=${constant}
highlight String guifg=${FG1}
highlight Character guifg=${FG1}
highlight Number guifg=${constant}
highlight Boolean guifg=${constant}
highlight Float guifg=${constant}

" Function highlighting
" Variables and identifiers
highlight Identifier guifg=${variable}
highlight @variable guifg=${variable}
highlight @variable.builtin guifg=${language}
highlight @variable.parameter guifg=${parameter}
highlight @variable.member guifg=${variableProperty}
highlight @property guifg=${property}
highlight @field guifg=${variableProperty}
highlight @parameter guifg=${parameter}
highlight @label guifg=${variable}

" Constants and attributes
highlight Constant guifg=${variableReadonly}
highlight @constant guifg=${variableReadonly}
highlight @constant.builtin guifg=${language}
highlight @attribute guifg=${attribute}
highlight @namespace guifg=${variable}

" Functions and methods
highlight Function guifg=${function}
highlight @function guifg=${function}
highlight @function.call guifg=${functionCall}
highlight @function.builtin guifg=${supportFunction}
highlight @method guifg=${method}
highlight @method.call guifg=${methodCall}
highlight @constructor guifg=${function}
highlight @decorator guifg=${functionCall}
highlight @annotation guifg=${functionCall}

" Statement and control flow
highlight Statement guifg=${AC2}
highlight Conditional guifg=${AC2}
highlight Repeat guifg=${AC2}
highlight Label guifg=${AC2}
highlight Operator guifg=${BORDER}
highlight Keyword guifg=${AC2}
highlight Exception guifg=${ERROR}

highlight Type guifg=${AC1}
highlight StorageClass guifg=${AC1}
highlight Structure guifg=${AC1}
highlight Typedef guifg=${AC1}

highlight Special guifg=${AC2}
highlight SpecialChar guifg=${AC2}
highlight Tag guifg=${AC2}
highlight Delimiter guifg=${BORDER}
highlight SpecialComment guifg=${comment}
highlight Debug guifg=${WARNING}

highlight Underlined guifg=${AC1} gui=underline
highlight Ignore guifg=${comment}
highlight Error guifg=${ERROR} guibg=${BG2}
highlight Todo guifg=${AC1} gui=bold,italic

" Plugin support
highlight CocErrorSign guifg=${ERROR}
highlight CocWarningSign guifg=${WARNING}
highlight CocInfoSign guifg=${INFO}
highlight CocHintSign guifg=${SUCCESS}
highlight CocHighlightText guibg=${selection}
highlight CocFloating guibg=${BG2}

" Treesitter
highlight @function guifg=${function}
highlight @function.call guifg=${functionCall}
highlight @method guifg=${method}
highlight @method.call guifg=${methodCall}
highlight @constructor guifg=${class}
highlight @parameter guifg=${parameter}
highlight @variable guifg=${variable}
highlight @variable.builtin guifg=${language}
highlight @constant guifg=${constant}
highlight @constant.builtin guifg=${language}
highlight @string guifg=${FG1}
highlight @character guifg=${FG1}
highlight @number guifg=${constant}
highlight @boolean guifg=${constant}
highlight @float guifg=${constant}
highlight @attribute guifg=${attribute}
highlight @namespace guifg=${variable}
highlight @keyword guifg=${keyword}
highlight @keyword.function guifg=${keyword}
highlight @keyword.operator guifg=${operator}
highlight @keyword.return guifg=${keyword}
highlight @operator guifg=${operator}
highlight @punctuation.bracket guifg=${punctuationBrace}
highlight @punctuation.delimiter guifg=${punctuation}
highlight @punctuation.special guifg=${punctuation}
highlight @tag guifg=${tag}
highlight @tag.delimiter guifg=${tagPunctuation}
highlight @tag.attribute guifg=${attribute}
highlight @type guifg=${type}
highlight @type.builtin guifg=${type}
highlight @type.definition guifg=${typeParameter}
highlight @type.qualifier guifg=${modifier}
highlight @storage guifg=${storage}
highlight @structure guifg=${type}
highlight @include guifg=${controlImport}
highlight @conditional guifg=${controlFlow}
highlight @repeat guifg=${controlFlow}
highlight @exception guifg=${controlFlow}
highlight @text guifg=${FG1}
highlight @text.strong guifg=${FG1} gui=bold
highlight @text.emphasis guifg=${FG1} gui=italic
highlight @text.underline guifg=${FG1} gui=underline
highlight @text.strike guifg=${FG1} gui=strikethrough
highlight @text.note guifg=${INFO}
highlight @text.warning guifg=${WARNING}
highlight @text.danger guifg=${ERROR}

" Markdown
highlight markdownH1 guifg=${AC1} gui=bold
highlight markdownH2 guifg=${AC2} gui=bold
highlight markdownH3 guifg=${BrightYellow} gui=bold
highlight markdownH4 guifg=${BrightGreen} gui=bold
highlight markdownH5 guifg=${BrightCyan} gui=bold
highlight markdownH6 guifg=${BrightBlue} gui=bold
highlight markdownBold guifg=${WARNING} gui=bold
highlight markdownItalic guifg=${ERROR} gui=italic
highlight markdownStrike guifg=${FG2} gui=strikethrough
highlight markdownUrl guifg=${INFO} gui=underline
highlight markdownUrlTitle guifg=${INFO}
highlight markdownCode guifg=${SUCCESS}
highlight markdownCodeLanguage guifg=${language}
highlight markdownCodeDelimiter guifg=${FG2}
highlight markdownBlockquote guifg=${punctuation}
highlight markdownRule guifg=${operator}
highlight markdownListMarker guifg=${unit}
highlight markdownOrderedListMarker guifg=${unit}
highlight markdownLinkText guifg=${INFO}
highlight markdownLinkDelimiter guifg=${punctuation}
highlight markdownLinkTextDelimiter guifg=${punctuation}
highlight markdownHeadingDelimiter guifg=${punctuation}
highlight markdownHeadingRule guifg=${punctuation}
highlight markdownUrlTitleDelimiter guifg=${other}
highlight markdownUrlDelimiter guifg=${other}
